name: Snapshot Build

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io
on:
  push:
    branches:
      - develop
      - pipeline
      - ci*
  pull_request:
    branches:
      - develop
      - main
  workflow_dispatch:

jobs:
  python:
    uses: ./.github/workflows/python-build-tests.yaml
    secrets:
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.MBZUAI_TOKEN }}
      REGISTRY_ADDRESS: ${{ secrets.REGISTRY_ADDRESS }}
  docker:
    needs: python
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build and publish docker snapshot
        uses: rampart-aios/github-actions/.github/actions/docker-snapshot-build@main
        with:
          IMAGE_NAME: ${{ github.repository }}
          CONTEXT: .
          # DOCKER_FILE: ./docker/Dockerfile.ui
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    